odoo: 
  command: 
    - "--"
  environment: 
    ADMIN_PASSWORD: "${admin_password}"
    PGHOST: db
    PGPASSWORD: "${pgpassword}"
    PGPORT: "${pgport}"
    PGUSER: "${pguser}"
  external_links: 
    - "${POSTGRESQL_SOURCE}:db"
  image: "claytonsilva/odoo:digital-ocean"
  labels: 
    io.rancher.container.hostname_override: container_name
  stdin_open: true
  volumes: 
    - "${odoo_dir}:/home/odoo/.local"
