.catalog:
  name: "Odoo"
  version: "0.1-gerencio"
  description: "ERP management powered by Odoo"
  uuid: odoo-0
  questions:
    - variable: POSTGRESQL_SOURCE
      description: "Link to postgresql service or stack/service"
      label: "Postgresql source"
      type: "service"
      required: true
    - variable: "admin_password"
      label: "Admin Password for Odoo"
      description: "Admin Password for Odoo"
      required: true
      type: "string"
    - variable: "pguser"
      label: "User Odoo for postgresql"
      description: "User Odoo for postgresql"
      required: true
      type: "string"
      default: "odoo"
    - variable: "pgpassword"
      label: "Password Odoo for postgresql"
      description: "Password Odoo for postgresql"
      required: true
      type: "string"
    - variable: "pgport"
      label: "TCP Port for postgresql"
      description: "TCP Port for postgresql"
      required: true
      type: "int"
      default: 5432
    - variable: "odoo_dir"
      label: "main dir to mount odoo"
      description: "main dir to mount odoo"
      required: true
      type: "string"
odoo:
  scale: 1
  retain_ip: true
  health_check:
    port: 8069
    interval: 30000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    healthy_threshold: 2
