name: Apache Mesos (Master)
description: |
  Apache Mesos (Master)
version: 0.2-veronica
category: clustering
maintainer: "CLayton Silva <clayton@xdevel.com.br>"
minimum_rancher_version: v0.56.0
license: 
